name: CI/CD Pipeline

# Déclencheurs du workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build API Dev Image
        run: docker build -f sdv-api/Dockerfile -t myapp-api-dev ./sdv-api

      - name: Build Web Dev Image
        run: docker build -f sdv-web/Dockerfile -t myapp-web-dev ./sdv-web

  push:
    name: Push Images
    runs-on: ubuntu-latest
    needs: build  # Cette phase ne s'exécute que si 'build' réussit

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub (First Repo)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_1 }}
          password: ${{ secrets.DOCKER_PASSWORD_1 }}

      - name: Tag and Push API Dev Image to First Repo
        run: |
          docker tag myapp-api-dev ${{ secrets.DOCKER_USERNAME_1 }}/sdv-api-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME_1 }}/sdv-api-dev:latest

      - name: Tag and Push Web Dev Image to First Repo
        run: |
          docker tag myapp-web-dev ${{ secrets.DOCKER_USERNAME_1 }}/sdv-web-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME_1 }}/sdv-web-dev:latest

      - name: Log in to Docker Hub (Second Repo)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_2 }}
          password: ${{ secrets.DOCKER_PASSWORD_2 }}

      - name: Tag and Push API Dev Image to Second Repo
        run: |
          docker tag myapp-api-dev ${{ secrets.DOCKER_USERNAME_2 }}/sdv-api-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME_2 }}/sdv-api-dev:latest

      - name: Tag and Push Web Dev Image to Second Repo
        run: |
          docker tag myapp-web-dev ${{ secrets.DOCKER_USERNAME_2 }}/sdv-web-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME_2 }}/sdv-web-dev:latest
