name: CI/CD Pipeline

# Déclencheurs du workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-dev:
    name: Build Dev Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build API Dev Image
        run: docker build -f sdv-api/Dockerfile --target dev -t myapp-dev ./sdv-api

      - name: Build Web Dev Image
        run: docker build -f sdv-web/Dockerfile --target dev -t myapp-web-dev ./sdv-web

  push-dev:
    name: Push Dev Image
    runs-on: ubuntu-latest
    needs: build-dev  # Exécute cette phase seulement si le job 'build-dev' réussit

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag API Dev Image
        run: docker tag myapp-dev ${{ secrets.DOCKER_USERNAME }}/sdv-api-dev:latest

      - name: Push API Dev Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sdv-api-dev:latest

      - name: Tag Web Dev Image
        run: docker tag myapp-web-dev ${{ secrets.DOCKER_USERNAME }}/sdv-web-dev:latest

      - name: Push Web Dev Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sdv-web-dev:latest
