jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image (production)
        uses: docker/build-push-action@v4
        with:
          context: ./sdv-api
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sdv-api:prod-latest
          target: prod

      - name: Build and push Frontend image (production)
        uses: docker/build-push-action@v4
        with:
          context: ./sdv-web
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sdv-web:prod-latest
          target: prod
